name = "cb16-ci-auth"
account_id = "25dea0f8748cc0d718d11a64983b4123"
main = "src/index.js"
compatibility_date = "2025-01-01"

workers_dev = false

[[routes]]
pattern = "ci-speedtest.bayesdesk.com/api/v1/worker/*"
zone_name = "bayesdesk.com"
