import math
from cb16_local_opt.cc_fast_account_state_r0 import *
from cb16_local_opt.cc_fast_account_kernel_r0 import *
CFG=AccountKernelConfig(fee_rate=0.0,maintenance_margin_fraction=0.0,liquidation_fee_rate=0.0)
def step(s,before,after,target,direction,risk=.2,status="ALLOW",funding=0): return step_account_scalar(s,0,account_lineage_id="a",environment_time_before_ns=int(before),environment_time_after_ns=int(before)+1,mark_price_before=float(after[0]),mark_price_after=float(after[1]),target_quantity=float(target),funding_rate=float(funding),policy_decision_ref="f"*64,permitted_target_direction=direction,permitted_target_risk=0.0 if direction=="FLAT" else risk,permission_status=status,permission_reason="fixture",config=CFG)
def test_open_reduce_close_reversal_order_and_mtm():
    s=AccountStateSoA.allocate(["a"],initial_equity=1000); r1=step(s,0,(100,110),2,"LONG"); assert math.isclose(s.equity[0],1020); r2=step(s,1,(110,105),-1,"SHORT"); assert [x.kind for x in r2.transition.execution_legs]==["REVERSAL_CLOSE","REVERSAL_OPEN"]; assert r2.transition.realized_pnl==20; r3=step(s,2,(105,115),99,"LONG",status="REJECT",funding=.001); assert s.quantity[0]==-1; assert r3.transition.funding!=0; assert r3.transition.environment_time_after_ns>r3.transition.environment_time_before_ns
def test_liquidation_records_terminal_and_no_clamp():
    s=AccountStateSoA.allocate(["a"],initial_equity=10); cfg=AccountKernelConfig(fee_rate=0.0,maintenance_margin_fraction=.2,liquidation_fee_rate=.0); r=step_account_scalar(s,0,account_lineage_id="a",environment_time_before_ns=0,environment_time_after_ns=1,mark_price_before=100,mark_price_after=10,target_quantity=1.0,funding_rate=0,policy_decision_ref="f"*64,permitted_target_direction="LONG",permitted_target_risk=.5,config=cfg); assert r.transition.mechanical_terminal is True; assert r.transition.boundary_type=="ECONOMIC_TERMINAL"; assert r.transition.execution_legs[-1].kind=="LIQUIDATION"; assert math.isfinite(r.transition.post_equity)
