LIFECYCLE_VERSION_R0="CB16_R11_CC_BAR_LIFECYCLE_V1_R0"
OBSERVATION_AVAILABLE="OBSERVATION_AVAILABLE"
DECISION_CAPTURED="DECISION_CAPTURED"
EXECUTION_APPLIED="EXECUTION_APPLIED"
ENVIRONMENT_APPLIED="ENVIRONMENT_APPLIED"
POST_STATE_PUBLISHED="POST_STATE_PUBLISHED"
PHASE_ORDER=(OBSERVATION_AVAILABLE,DECISION_CAPTURED,EXECUTION_APPLIED,ENVIRONMENT_APPLIED,POST_STATE_PUBLISHED)
def next_phase_r0(phase:str)->str:
    if phase not in PHASE_ORDER: raise RuntimeError("CCLIFE_PHASE_INVALID")
    i=PHASE_ORDER.index(phase)
    if i==len(PHASE_ORDER)-1: raise RuntimeError("CCLIFE_ALREADY_PUBLISHED")
    return PHASE_ORDER[i+1]
